### ISSUE TITLE
Write Lesson 5

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/academy#110]

**Comment by losMacos** [comment]
Fundamentals: 

- Rainbowkit
- Wagmi
- EthersJS

**Comment by ropats16** [comment]
Hey mate added links to their docs.
- [Rainbowkit](https://www.rainbowkit.com/docs/introduction) provides out of the box wallet management. You can customise chains, various wallet apps, connect wallet button, custom themes.
- [WAGMI](https://wagmi.sh/) gives a bunch of hooks that allow you to fetch wallet addresses, interact with contracts, read information, call functions, among other things.
- EtherJS could just be a part of WAGMI as WAGMI is built using ethers. Just a couple of lines of what functions ethers provided perhaps.
