### ISSUE TITLE
Add Privacy Policy to website. Remove Google Analytics.

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/academy#137]

**Comment by kempsterrrr** [comment]
@briangershon this is in my backlog of todo's, we also need T&Cs. Are we collecting any data from folks atm?

**Comment by hardiktheprogrammer** [comment]
yes it is important

**Comment by briangershon** [comment]
We're using Google Analytics to collect site usage data.

Also, visitors can opt out.

**Comment by kempsterrrr** [comment]
I've added this to me todo's this week @briangershon - is Google Analytics the only way we're tracking folks at the moment?

**Comment by briangershon** [comment]
Thank you! Yes, just GA.

**Comment by kempsterrrr** [comment]
@briangershon apologies didn't get around to this but haven't forgotten. Out of interest have you considered using Vercel's new [built-in audience tool](https://vercel.com/analytics)?

**Comment by kempsterrrr** [comment]
@briangershon Reason I asked about ☝🏻 is its GDPR friendly where as Google Analytics is not so easier manage from a data perspective. If we're only using Google analytics for the basic features you get from adding the script tag to the website vs the more complex tracking you can do with customer events etc. maybe we can get what we want for free and in a less smelly way with Vercel's built-in feature

**Comment by briangershon** [comment]
Merged https://github.com/Developer-DAO/academy/pull/174 which added Vercel Analytics.

We'll compare that for a bit with GA analytics... then we can remove GA analytics at some point in the future.

**Comment by kempsterrrr** [comment]
Thanks, @briangershon - have we removed GA?

Here is a [blank doc](https://docs.google.com/document/d/1Hw19Lmb33945V5fC5_GV_U4JG1Ep8WdgCkim6LVB-kc/edit?usp=sharing) for the academy policy and a link to the [D_D policy](https://www.developerdao.com/privacy-policy) for reference. Will add you to the doc via email.

**Comment by briangershon** [comment]
Finally got around to removing GA.

Hey @kempsterrrr do you think a privacy policy is needed now that GA is removed? If yes, should we just put a link in the footer and point to https://www.developerdao.com/privacy-policy that you mentioned above?

**Comment by kempsterrrr** [comment]
@briangershon thanks for the ping. Yes, please just point to that for now :)
