### ISSUE TITLE
Fix Side Drawer Button Styling for Smaller Devices

### ISSUE THREAD

**Issue by ropats16** [Developer-DAO/academy#141]
- Some side drawer buttons in lesson 1 seem to have text very close to the arrow icon on the iPhone 12 Pro sized devices. Perhaps font sizing needs to be dynamic for these.
![image](https://user-images.githubusercontent.com/50047129/191446296-6f3c7d87-c59b-458b-bd87-164494fe30cc.png)

- On the same device sizes and in the same lesson, some buttons seem to have variable heights that break on multiline text. The height needs to be responsive to accomodate the text. Or the dynamic font sizing above might solve this issue.
![image](https://user-images.githubusercontent.com/50047129/191446971-6d7c1a6a-8aac-47fb-ba88-cf1f240fd5aa.png)

**Comment by briangershon** [comment]
PR merged!
