### ISSUE TITLE
Add authors to Lessons and Fundamentals

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/academy#145]
I remember seeing a suggestion about adding authors.

I think this would be very beneficial. It gives kuddos to the authors, and may be important for partnerships as well.

**Comment by briangershon** [comment]
Hey @PBillingsby here's a placeholder issue for adding authors, if you want to use this one!

**Comment by PBillingsby** [comment]
@briangershon will use this one! Thanks mate

**Comment by briangershon** [comment]
Replaced by #193
