### ISSUE TITLE
Add live site link to readme

### ISSUE THREAD

**Issue by traversng** [Developer-DAO/academy#19]
Anyone coming to this repo should be able to view the live site online for context.

**Comment by briangershon** [comment]
Thanks @traversng, we'll make sure we add once we go live.

**Comment by traversng** [comment]
Hey @briangershon , I want to make some contributions to the site, can you please add me to the org?

**Comment by briangershon** [comment]
Once we go live with https://github.com/Developer-DAO/academy/issues/111 we can update README to point to `https://academy.developerdao.com`

**Comment by briangershon** [comment]
- I've updated README: https://github.com/Developer-DAO/academy/commit/31c5fd04e4c0b49c630620bd7aaacb9f3632a83c
- I updated link in GitHub's "about repo" viewable when visiting GitHub repo's home page.
