### ISSUE TITLE
Feature: Highlight Content Authors and Reviewers; plus link to Peeranha forum.

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/academy#193]
## Goals

- Primarily highlight content author. Inlude a PFP image, name, organization name and a link to their personal site.
- Secondarily highlight all reviewers and contributors
- Link to a specific topic on Peeranha forum so users can ask questions and have discussions. For example [Lesson 4: Testing your TierNFT](https://academy.developerdao.com/lessons/projects/4) would point to [Testing Solidity contracts topic](https://developerdao.peeranha.io/discussions/1372/testing-solidity-contracts) in Peeranha.

Other goals:

- Create a consistent header and footer to use for all content tracks and fundamentals
- Add a general link to our Peeranha community in Footer and Getting Started - https://developerdao.peeranha.io
- All information should be viewable on rendered page for SEO.

## Implementation Ideas

- A content header with title of content, Author info and a link to the Peeranha forum.
- A content footer with list of reviewers and contributors

## Work Involved

- Product and Design concepts and iterations
- Create React components; styling; iterations -- header and footer
- Store author, reviewer and contributor information -- yaml front-matter or a data file? Data file may work better to also support a more detailed author bio page.

**Comment by georgemac510** [comment]
Really cool idea to get going on Peeranha @briangershon! You referenced Lesson #4 in your example. Could we do the same for a fundamentals lesson where we were the author?

**Comment by briangershon** [comment]
Hey @georgemac510,

Yes, building it with one lesson, but once working we can apply to all lessons and fundamentals.
