### ISSUE TITLE
Pomodoro Timer

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/academy#20]
# What is Pomodoro?

One of this project's [3-month goals](https://developerdao.notion.site/Developer-DAO-School-of-Code-e57edcdcc3ec4cdaad9ae592f9f86086#b9e157ba69bc41b6ad31bb99da55041b) is to add a Pomodoro Timer feature:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/1954752/175327395-38f01e27-3b27-4600-88b8-7cea8a307e1d.png">

In case you're not familiar with the Pomodoro Technique, here's an overview:

![image](https://user-images.githubusercontent.com/1954752/175347445-d2dbb0ea-943d-4183-a167-99820c37aa9e.png)

You can also visit https://pomofocus.io/ to try out a timer!

This method of working is effective for a few reasons:

- listing your tasks helps you remain focused on the things you're trying to accomplish
- the timer encourages you to _just start_ and oftentimes just starting creates the motivation and clarity needed to _keep going_
- the timer encourages a consistent rhythm of breaks which is a healthy habit
- coming back from a break forces you to think about what you'll try to accomplish with the next session, adding a little bit more mindfulness to your working process

# What are we building?

Since we know we want to have this as a feature but we don't know how we'll use it exactly, this issue is for creating a minimal component that exists only in Storybook (see #18) for the time being. This allows us to focus on building a solid foundation for the component which we can build on top of once we better understand where we'll use it, how it should look, and what other features we want it to have.

That minimal component is essentially number 2 from the above image: a timer for handling loops of 25 minutes study -> 5 minutes break

That might not seem like enough to justify the effort of putting together this detailed issue, but there's actually quite a bit of complexity hidden in here. For example, here are the different states this component might be in:

![image](https://user-images.githubusercontent.com/1954752/175750604-f0b7b8a2-0d02-4572-8cc8-949936e6d321.png)

Each of those buttons leads us to a different state:

![image](https://user-images.githubusercontent.com/1954752/175750765-cb28f055-6b35-415e-a1cd-3f509746b99f.png)

And some of these states might even have some special behaviors we need to add too:

![image](https://user-images.githubusercontent.com/1954752/175750853-c1dd8edb-7f31-4b02-ba56-eeddfc0b285b.png)

# Acceptance Criteria

In order to know when this issue can be considered _done_, I've created a list of _acceptance criteria_ to define the specific behaviors of this component. Before we get to that, let's define a few terms:

- "full timer" refers to the timer before it has started counting down. For a study session this is 25:00 and for a break session, this is 05:00
- "active timer" refers to a timer that is counting down second by second to 0
- "paused timer" refers to a running timer that has been paused, meaning the timer remains at the current remaining time until it is resumed
- "empty timer" refers to a timer that has counted all the way down to 0. An empty timer should never go into the negative, meaning that it stops counting down at 00:00.

With those terms out of the way, here are the acceptance criteria for this component:

- The timer starts in the idle state
- An idle timer displays a full timer for a study session (25:00) and allows the user to start a study session
- A full study session timer begins at 25:00
- An active study session timer counts down second by second to 00:00
- An active study session timer can be paused
- An active study session timer can be reset back to the idle state
- A paused study session timer can be resumed
- A paused study session can be reset back to the idle state
- An empty study session timer can begin a break session
- A full break session timer begins at 05:00
- An active break timer can be skipped which returns the timer to the idle state
- An empty break timer allows the user to start a new study session timer
- Times are always displayed in the "MM:SS" format (examples: "25:00", "24:59", "09:59", "00:00")

**Comment by with-heart** [comment]
I've assigned this task to myself because I believe it's a good opportunity to cover a start-to-finish process for defining a new feature and then implementing it:

- create an issue that clearly defines the _context_ of the new feature (this issue)
  - what is the proposed feature?
  - why is it important?
  - how could we go about implementing it?
  - acceptance criteria
- define the acceptance criteria as tests
- implement the component so that the tests pass
- create a pull request that explains how we went about implementing the component and documents the decisions we made in doing so

**Note:** Not all of these are always required for every new feature. Sometimes you just have an idea want to share (the _what_ and the _why_) and don't have all of the specifics figured out (the _how_ and the _acceptance criteria_) so the issue is missing the specifics and that's totally fine. Sometimes you don't need/want to write tests for what you're working on because you're experimenting with an idea/it's not worth testing/etc.

The whole process is quite abstract and changes based on all sorts of factors. This is just a clear example of a thorough process for a well-defined issue, and I think doing the work myself and clearly documenting it through this issue and the resulting PR will provide a lot of knowledge to contributors of this project:

- how to create a good issue
- how to turn an idea into an implementation
- how to test a component's behavior
- how to write tests _before_ the implementation
- why writing tests can sometimes be a useful guide for the work we need to perform
- how to implement a complex component with many states in a manageable way
- how to create a good pull request

That's a lot of goodness! I'll use this issue to tell a story of what I'm doing as I go, so that yall can follow along and learn some things! ❤️

**Comment by NickWhiteman** [comment]
can i check the kits for you?
