### ISSUE TITLE
Improve SEO: First 5 Fundamental Lessons

### ISSUE THREAD

**Issue by okhaimie-dev** [Developer-DAO/academy#214]
We need to homogonise lesson titles and descriptions (including in the lesson body .mdx texts)

The titles in the front matter in the .mdx files don't match the titles in the 'Tracks' or 'Get Started' landing pages. It would be nice to use the same titles in all places including in the lessons.

Also, we need to take into consideration of the descriptions of the lessons in 'Tracks' and also in the lessons themselves. Quite often in these two places, we refer to e.g. lesson 1, or lesson 4 when these 'numbers' aren't represented in the actual lesson titles.

**Comment by elPiablo** [comment]
NIce one Okhai for opening this 😄 
I found this quite handy to have an overview of what the present state of affairs is with the NFT track lessons - to use as a starting point: https://github.com/Developer-DAO/academy/issues/205#issuecomment-1636276567

**Comment by okhaimie-dev** [comment]
Thanks for sharing @elPiablo comment. About to work on this task for a bit right now.

**Comment by okhaimie-dev** [comment]
@elPiablo I updated the titles to a similar format as example shown below. 

P.S. Code branch was derived off `quiz-lesson-4` and I intend to make a PR back to that or any branch the parent branch is merged into.

## After
<img width="1114" alt="CleanShot 2023-07-23 at 23 02 25@2x" src="https://github.com/Developer-DAO/academy/assets/57156589/cd9de499-ab7e-4091-adf3-ca09f11e6ccc">

## Before
<img width="1156" alt="CleanShot 2023-07-23 at 23 01 18@2x" src="https://github.com/Developer-DAO/academy/assets/57156589/34d867a0-17e6-4168-a890-f2a1cc0e484e">


```mdx
<LessonHeader 
    title="Fundamentals: Getting Started with the Command Line Interface"
/>
```
I didn't add the optional discussion link props as there is none for this fundamental courses. Do you want me to create one?

```tsx
export function LessonHeader({ title, discussionUrl }: LessonHeaderProps) {
  let forumLink = discussionUrl || DEFAULT_DISCUSSION_URL

  return (
    <Box>
      <Box>
        <Text
          mt="1.5em"
          fontWeight="bold"
          fontSize="1.875rem"
          letterSpacing={-0.025}
          color="yellow.300"
        >
          {title}
        </Text>
      </Box>
      {forumLink && (
        <HStack marginY={6} columnGap={2} maxWidth="xl">
          <Box>
            <QuestionIcon w={8} h={8} />
          </Box>
          <Box>
            If you get stuck or have questions please visit our{' '}
            <Link
              as={NextLink}
              href={forumLink}
              passHref
              isExternal
              textDecoration="underline"
            >
              forum
            </Link>
            .
          </Box>
        </HStack>
      )}
    </Box>
  )
}
```

I am still looking at some extra steps I can work on to include the page SEO, just thought to leave an update.

**Comment by elPiablo** [comment]
> @elPiablo I updated the titles to a similar format as example shown below.

Hey @okhaimie-dev :)
So far, the name of the track is going to be 'Fundamentals', so I don't think it is necessary in the actual title.

**Comment by elPiablo** [comment]
> P.S. Code branch was derived off quiz-lesson-4 and I intend to make a PR back to that or any branch the parent branch is merged into.

Would it be an idea to just create a separate branch for the work on these issues? Branch for quiz-lesson-4 was getting quite a lot of changes to the .mdx and new files being created to house the quizzes and questions. And Marc and Brian were reviewing those each time I do changes. It might get messy if there is other work going on on that branch elsewhere too.

**Comment by elPiablo** [comment]
@okhaimie-dev 

> I didn't add the optional discussion link props as there is none for this fundamental courses. Do you want me to create one?

Good question, Tony. John mentioned this a while ago, I think. Do we really want to have to maintain/moderate these fundamentals' content pieces on Peeranha? Or should we only add links for fundamentals that are a tutorial? Would you mind putting this question on the agenda for Thursday's weekly sync? I'll pop a link into the #academy channel somewhere and tag you. In the meantime, is it possible just to put that placeholder code in for now, or is that bad practice?


> Also, below is an example of the LessonHeader component, and it accepts only two props. Do you want me to modify this so it can accommodate a similar input as what you suggested in your comment https://github.com/Developer-DAO/academy/issues/205#issuecomment-1636276567?

I think it's correct that it only has those two props (`title` and `discussionUrl`).

**Comment by okhaimie-dev** [comment]
> Would it be an idea @okhaimie-dev to just create a separate branch for the work on these issues?

I created a new branch `fundamental-lesson-seo` but it is a branch off `quiz-lesson-4` = I can wait till you merge that to `develop` before I merge mine and we should be fine. Or I can merge the seo fix back to `quiz-lesson-4`.

I am 100% sure there will be no merge conflicts this way

**Comment by okhaimie-dev** [comment]
> > @elPiablo I updated the titles to a similar format as example shown below.
> 
> Hey @okhaimie-dev :) So far, the name of the track is going to be 'Fundamentals', so I don't think it is necessary in the actual title.

Alright. I will take out the "Fundamentals" prefix

**Comment by okhaimie-dev** [comment]
@kempsterrrr 

Seeing as you have spent more time working on this project, I believe you are better suited to drive the S.E.O. work. If you don't mind starting the new thread, then we can close the other two issue on for the S.E.O. 

I'll still love to learn the best strategies on S.E.O. from you, so I will watch how your approach it this time, and will be happy to assist when the need arises.

**Comment by elPiablo** [comment]
Sounds good to open a fresh issue with this folks. Do we delete the present issues? Or do these present ideas get integrated to the new one?

Do these proposals influence your work flow @uma-l? Just want to make sure you're up to speed with all this. 

And should we @wolovim and I not change any titles/text at this stage in the lesson reviews we're doing? (not a big deal right now, but nice to know). 

IN this new issue, could we maybe have some kind of rough timeline + implementation of changes + features. Something simple/visual to get our heads around?

Cheers

**Comment by kempsterrrr** [comment]
@elPiablo why don't we close this issue and instead continue the conversation in #205 ?

I can lay out a timeline in there if you're happy with that, with the goal of creating a clear set of deliverables to update the SEO structure of the site.

The main changes I imagine that might impact Uma are :

1) Designing specific landing pages for things like `/learn-solidity` if we end up going that route
2) Creating some visual assets for meta images

But let's have that conversation on the other issue if/when we get to that :)

Optimistically closing this issue - re-open if you want :)

**Comment by elPiablo** [comment]
sounds good to me that you closed this @kempsterrrr :)
