### ISSUE TITLE
update lesson2 code for new ethers version

### ISSUE THREAD

**Issue by elPiablo** [Developer-DAO/academy#235]
- [x] ethers.js got quite an upgrade recently and the code in the deploy.js script and the accompanying instructions in the lesson body need to be updated. 

- [x] Please also check if `npx hardhat run scripts/deploy.js` works correctly, or if we need to change it to `npx hardhat run scripts/deploy.js --network hardhat`. the reason for this comment is because the former command is causing errors with lesson 3's mint.js output.

- [x] change network from Goerli to Sepolia
- [x] check quiz questions still make sense regarding the above updates

**Comment by ocdbytes** [comment]
Hey @elPiablo 

I am open to help you in this issue. I myself am a member of developer dao and familiar with the development in Web3.

**Comment by JakeDamon** [comment]
What's the status on this @elPiablo?
I'd like to help if possible.

**Comment by elPiablo** [comment]
Hey @ocdbytes and @JakeDamon ,
Nice to hear interest from you both! 
Re: this issue, it's a PR awaiting a final review, then ready to merge: https://github.com/Developer-DAO/academy/pull/236
Would you both like to join the Academy weekly sync on Developer DAO Discord tomorrow (Thursday): https://discord.com/channels/883478451850473483/885167810949546036/1146867069535658135

**Comment by JakeDamon** [comment]
Okay, I'll be there tomorrow @elPiablo :)

**Comment by elPiablo** [comment]
All done :)
