### ISSUE TITLE
Feat: Add email capture banner

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/academy#242]
As per the discussions in [this thread](https://discord.com/channels/883478451850473483/1151143644066222101) in Discord, I believe it's essential we start marketing the upcoming V2 of the academy.

I propose a very simple change to add a banner to the top of every page with a message along the lines for - "Version 2 of Academy is coming, subscribe to updates or contact us for partnerships"

https://tailwindui.com/components/marketing/elements/banners

**Comment by okhaimie-dev** [comment]
Fix: https://github.com/Developer-DAO/academy/pull/243
