### ISSUE TITLE
Add mobile responsive landing and styling

### ISSUE THREAD

**Issue by PBillingsby** [Developer-DAO/academy#26]
The current landing page of the app isn't mobile responsive based on the figma.
https://www.figma.com/file/vpd1sJNOXS6WXclyZ5Av6U/Diagram---School?node-id=860%3A30587

This issue is for adding responsiveness to the landing page.

Current:
![Screen Shot 2022-07-06 at 8 35 06 PM](https://user-images.githubusercontent.com/45179070/177685451-17998a26-485a-4063-9c75-0242073a4032.png)

The Developer DAO logo in the current image above is the one we are using but the padding needs to match the figma.

Needed:
![Screen Shot 2022-07-06 at 8 28 25 PM](https://user-images.githubusercontent.com/45179070/177685524-11ae0f21-6cf8-44e2-9b31-c2ab666e9ec1.png)

**Comment by briangershon** [comment]
Hey @personnamedmike

I noticed PR #29 for this, but it has the same issues as PR #28 which is 1000+ file changes.

I'd recommend we close #29 and then you could just open a PR with this [1 file change](https://github.com/Developer-DAO/school-of-code/pull/29/files#diff-a705902108330efeeffcb3ff25696c3982c311b332b1a3d1007b70468080b5f0R2) in `Header.tsx` and we could review that.

**Comment by briangershon** [comment]
I closed #29 but we can pluck out the changes if still needed.

**Comment by briangershon** [comment]
Closing this issue due to age.
