### ISSUE TITLE
Have intermediate page linking to both "fundamentals" track and "projects" track

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/academy#38]
When user clicks "getting started" on home page, they'll come to this new page (/tracks) and then two new sub-directories for the types of tracks (/tracks/fundamentals and /tracks/projects).

(no more `/lessons` -- would be fundamentals or projects)

Include:
- New page
- Routing and slugs (e.g. /tracks)

**Comment by ropats16** [comment]
Hey @briangershon do you think we can close this issue? We have a tracks page that serves as the intermediary.

**Comment by briangershon** [comment]
Yes, sounds good -- closing!
