### ISSUE TITLE
add favicons for all platforms and webmanifest

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/academy#40]
See PR that was used to add the official D_D circular favicon in Pixel Devs: https://github.com/Developer-DAO/pixel-avatars/pull/115

**Comment by frankiefab100** [comment]
Let me fix this

**Comment by briangershon** [comment]
Thanks @frankiefab100 for picking this up!

**Comment by briangershon** [comment]
Hey @frankiefab100 just running through issues, and noticed this has a self-merge PR #45 but the PR shows no code merged, which I haven't seen. Is this issue still in progress? Thanks!

**Comment by frankiefab100** [comment]
> Hey @frankiefab100 just running through issues and noticed this has a self-merge PR #45 but the PR shows no code merged, which I haven't seen. Is this issue still in progress? Thanks!

I noticed It got merged the moment you reviewed it and suggest I add web manifest and other stuff.

**Comment by briangershon** [comment]
Hey @frankiefab100

I had just saw this about the merge:

<img width="865" alt="Screen Shot 2022-09-03 at 8 04 01 PM" src="https://user-images.githubusercontent.com/139330/188295273-e110ed36-765a-4c8a-b886-49714b693759.png">

But no worries! Did you want to continue to work on? I can also try to find some additional hands to help too!

**Comment by frankiefab100** [comment]
> Hey @frankiefab100
> 
> I had just saw this about the merge:
> 
> <img alt="Screen Shot 2022-09-03 at 8 04 01 PM" width="865" src="https://user-images.githubusercontent.com/139330/188295273-e110ed36-765a-4c8a-b886-49714b693759.png">
> 
> (It's possible I accidentally merged or something, and Github shows your name next to because you created PR? I'm not really sure what happened.)
> 
> But no worries! Did you want to continue to work on? I can also try to find some additional hands to help too!

Yes, I will love to continue working on this.

**Comment by frankiefab100** [comment]
@briangershon is this issue resolved?

**Comment by briangershon** [comment]
Hey @frankiefab100 no worries, I have a bit of time today and will wrap this one up!

**Comment by frankiefab100** [comment]
> Hey @frankiefab100 no worries, I have a bit of time today and will wrap this one up!

Alright
