### ISSUE TITLE
Measuring Season 1 Goals

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/academy#44]
Two goals of Season 1 are to:
- successfully onboard 250 members to the platform
- and ensure 50 members complete 100% of track

How are these metrics defined, and how do we measure them?

**Comment by georgemac510** [comment]
Could it be, for data analytics as well, different category of visitor(i.e. information seeker on the lower end of engagement versus full engagement measured by student uses the resources offered to complete a lesson/unit deliverable such as a unit project)?

@ropats16 mentioned a visitor counter. Anyway to use counters on each lesson to gauge visitor/student engagement? Of course, this is all post-MVP stuff, but I think you are right @briangershon to start considering it,

**Comment by script-money** [comment]
Some other similar programs, such as _buildspace_ and _road to web3_, they issue NFT to participants who complete the course, and it would be easy to reach the goal with such a design.

**Comment by briangershon** [comment]
Thanks @script-money for your feedback! Sorry for the belated response.

I'm going to close this issue and we can continue conversation in #66 -- one of the ideas there is to offer NFTs after completing courses. The first challenge will be deciding how courses are completed -- via a quiz, building a sample project, automated testing of contracts build, etc.
