### ISSUE TITLE
What license is our content?

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/academy#61]
- [x] We should pick a license for our content -- I'd say mainly check out https://creativecommons.org/ -- they have a "Choose a License" feature: https://creativecommons.org/share-your-work/
- [x] And note it our repo README
- [x] Mention it in our footer.

**Comment by PBillingsby** [comment]
Hmm. Could have sworn we’d created the project with an MIT license. Guess not!

See any problems with just using one of those? Or are you thinking of a different type of license? @briangershon

**Comment by briangershon** [comment]
Hey @PBillingsby

I was thinking about a separate content license, such as choosing one of the Creative Commons ones.

cc: @meowyx @ropats16 

ps: I just added an MIT license for us in https://github.com/Developer-DAO/school-of-code/pull/68

**Comment by elPiablo** [comment]
Hey @briangershon , 
I like the sound of what Creative Commons' values seem to be!

**Comment by ropats16** [comment]
This should be pretty simple. Based on this selector https://creativecommons.org/choose/ from Creative Commons, choosing the options of allowing others to share adaptations of our work but preventing commercial use of the work, we get the [Attribution-NonCommercial 4.0 International](http://creativecommons.org/licenses/by-nc/4.0/) License. We can change this later if a better fit is needed but at the moment as our work is out there, a license is important.

cc: @PBillingsby @elPiablo @7i7o @georgemac510 @wolovim

**Comment by briangershon** [comment]
Yes, let's add the license and highlight it in the README.
